"""Initial Schema Fixed

Revision ID: 3d543f5938f3
Revises: 
Create Date: 2025-12-29 11:26:09.669242

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d543f5938f3'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('msb_license',
    sa.Column('jurisdiction', sa.String(length=50), nullable=False),
    sa.Column('license_number', sa.String(length=100), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('issued_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expiration_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('renewal_due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('document_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number')
    )
    op.create_index(op.f('ix_msb_license_jurisdiction'), 'msb_license', ['jurisdiction'], unique=False)
    op.create_table('price_snapshot',
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('market_cap', sa.Numeric(precision=36, scale=4), nullable=True),
    sa.Column('total_volume_24h', sa.Numeric(precision=36, scale=4), nullable=True),
    sa.Column('snapshot_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('coin_id', 'currency', 'snapshot_at', 'id')
    )
    op.create_index(op.f('ix_price_snapshot_coin_id'), 'price_snapshot', ['coin_id'], unique=False)
    op.create_table('smart_contract',
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('contract_type', sa.Enum('PAYMENT_ROUTER', 'STAKING_POOL', 'ESCROW', name='smartcontracttype'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('abi_encrypted', sa.Text(), nullable=True),
    sa.Column('deployment_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('chain', 'contract_type', 'version', 'id')
    )
    op.create_index(op.f('ix_smart_contract_address'), 'smart_contract', ['address'], unique=False)
    op.create_index(op.f('ix_smart_contract_chain'), 'smart_contract', ['chain'], unique=False)
    op.create_index(op.f('ix_smart_contract_contract_type'), 'smart_contract', ['contract_type'], unique=False)
    op.create_index(op.f('ix_smart_contract_is_active'), 'smart_contract', ['is_active'], unique=False)
    op.create_table('user_account',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('hashed_pin', sa.String(length=255), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MERCHANT', 'ADMIN', name='userrole'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'SUSPENDED', 'PENDING', 'LOCKED', name='userstatus'), nullable=False),
    sa.Column('kyc_level', sa.Enum('NOT_STARTED', 'PENDING', 'APPROVED_LEVEL_1', 'APPROVED_LEVEL_2', 'APPROVED_LEVEL_3', 'REJECTED', 'NOT_VERIFIED', 'SUBMITTED', name='kycstatus'), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_account_email'), 'user_account', ['email'], unique=False)
    op.create_index(op.f('ix_user_account_is_deleted'), 'user_account', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_user_account_username'), 'user_account', ['username'], unique=False)
    op.create_index('ix_user_email_active', 'user_account', ['email'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_index('ix_user_username_active', 'user_account', ['username'], unique=True, postgresql_where=sa.text('is_deleted = false'))
    op.create_table('address_whitelist',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'chain', 'address', name='_user_chain_address_uc')
    )
    op.create_index(op.f('ix_address_whitelist_address'), 'address_whitelist', ['address'], unique=False)
    op.create_index(op.f('ix_address_whitelist_user_id'), 'address_whitelist', ['user_id'], unique=False)
    op.create_table('blockchain_screening',
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('risk_score', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('risk_rating', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='riskrating'), nullable=False),
    sa.Column('action_taken', sa.Enum('ALLOWED', 'FLAG_FOR_REVIEW', 'BLOCKED', name='screeningaction'), nullable=False),
    sa.Column('provider_response', sa.Text(), nullable=True),
    sa.Column('screening_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_blockchain_screening_action_taken'), 'blockchain_screening', ['action_taken'], unique=False)
    op.create_index(op.f('ix_blockchain_screening_address'), 'blockchain_screening', ['address'], unique=False)
    op.create_index(op.f('ix_blockchain_screening_chain'), 'blockchain_screening', ['chain'], unique=False)
    op.create_index(op.f('ix_blockchain_screening_risk_rating'), 'blockchain_screening', ['risk_rating'], unique=False)
    op.create_index(op.f('ix_blockchain_screening_user_id'), 'blockchain_screening', ['user_id'], unique=False)
    op.create_table('internal_ledger',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('transaction_id', sa.String(length=255), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('entry_type', sa.Enum('DEPOSIT', 'WITHDRAWAL', 'ONRAMP_PURCHASE', 'INTERNAL_TRANSFER', 'MERCHANT_PAYMENT', 'STAKING_REWARD', 'FEE', 'SETTLEMENT', name='ledgerentrytype'), nullable=False),
    sa.Column('related_user_id', sa.UUID(), nullable=True),
    sa.Column('related_tx_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['related_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_ledger_entry_type'), 'internal_ledger', ['entry_type'], unique=False)
    op.create_index(op.f('ix_internal_ledger_related_tx_hash'), 'internal_ledger', ['related_tx_hash'], unique=False)
    op.create_index(op.f('ix_internal_ledger_related_user_id'), 'internal_ledger', ['related_user_id'], unique=False)
    op.create_index(op.f('ix_internal_ledger_token_symbol'), 'internal_ledger', ['token_symbol'], unique=False)
    op.create_index(op.f('ix_internal_ledger_transaction_id'), 'internal_ledger', ['transaction_id'], unique=True)
    op.create_index(op.f('ix_internal_ledger_user_id'), 'internal_ledger', ['user_id'], unique=False)
    op.create_table('kyc_submission',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('external_submission_id', sa.String(length=255), nullable=True),
    sa.Column('level', sa.Enum('NOT_STARTED', 'LEVEL_1', 'LEVEL_2', 'LEVEL_3', name='kyclevel'), nullable=False),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PENDING', 'APPROVED_LEVEL_1', 'APPROVED_LEVEL_2', 'APPROVED_LEVEL_3', 'REJECTED', 'NOT_VERIFIED', 'SUBMITTED', name='kycstatus'), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_kyc_submission_external_submission_id'), 'kyc_submission', ['external_submission_id'], unique=True)
    op.create_index(op.f('ix_kyc_submission_user_id'), 'kyc_submission', ['user_id'], unique=False)
    op.create_table('merchant',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('registration_number', sa.String(length=100), nullable=True),
    sa.Column('business_address', sa.Text(), nullable=True),
    sa.Column('kyc_status', sa.Enum('NOT_STARTED', 'PENDING', 'APPROVED_LEVEL_1', 'APPROVED_LEVEL_2', 'APPROVED_LEVEL_3', 'REJECTED', 'NOT_VERIFIED', 'SUBMITTED', name='kycstatus'), nullable=False),
    sa.Column('settlement_frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', name='settlementfrequency'), nullable=False),
    sa.Column('settlement_wallet_address', sa.String(length=255), nullable=True),
    sa.Column('settlement_chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=True),
    sa.Column('settlement_token_symbol', sa.String(length=20), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'id'),
    sa.UniqueConstraint('user_id', name='uq_merchant_user_id')
    )
    op.create_index(op.f('ix_merchant_business_name'), 'merchant', ['business_name'], unique=False)
    op.create_index(op.f('ix_merchant_kyc_status'), 'merchant', ['kyc_status'], unique=False)
    op.create_index(op.f('ix_merchant_registration_number'), 'merchant', ['registration_number'], unique=False)
    op.create_table('portfolio',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_portfolio_user_id'), 'portfolio', ['user_id'], unique=False)
    op.create_table('price_alert',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('coin_id', sa.String(length=100), nullable=False),
    sa.Column('target_price', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('direction', sa.Enum('ABOVE', 'BELOW', name='pricealertdirection'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'TRIGGERED', 'INACTIVE', name='pricealertstatus'), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_alert_coin_id'), 'price_alert', ['coin_id'], unique=False)
    op.create_index(op.f('ix_price_alert_status'), 'price_alert', ['status'], unique=False)
    op.create_index(op.f('ix_price_alert_user_id'), 'price_alert', ['user_id'], unique=False)
    op.create_table('pull_payment_approval',
    sa.Column('approver_user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_address', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('token_address', sa.String(length=255), nullable=True),
    sa.Column('spending_limit', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='subscriptionfrequency'), nullable=False),
    sa.Column('current_period_spent', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('period_end_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'COMPLETED', name='subscriptionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['approver_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pull_payment_approval_approver_user_id'), 'pull_payment_approval', ['approver_user_id'], unique=False)
    op.create_index(op.f('ix_pull_payment_approval_period_end_date'), 'pull_payment_approval', ['period_end_date'], unique=False)
    op.create_index(op.f('ix_pull_payment_approval_recipient_address'), 'pull_payment_approval', ['recipient_address'], unique=False)
    op.create_index(op.f('ix_pull_payment_approval_status'), 'pull_payment_approval', ['status'], unique=False)
    op.create_table('staking_position',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('apy_at_stake', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('is_compounding', sa.Boolean(), nullable=False),
    sa.Column('start_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('protocol_address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_staking_position_token_symbol'), 'staking_position', ['token_symbol'], unique=False)
    op.create_index(op.f('ix_staking_position_user_id'), 'staking_position', ['user_id'], unique=False)
    op.create_table('subscription',
    sa.Column('subscriber_user_id', sa.UUID(), nullable=False),
    sa.Column('recipient_address', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('token_address', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'YEARLY', name='subscriptionfrequency'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'CANCELLED', 'COMPLETED', name='subscriptionstatus'), nullable=False),
    sa.Column('next_execution_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_execution_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_contract_address', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['subscriber_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_subscription_next_execution_date'), 'subscription', ['next_execution_date'], unique=False)
    op.create_index(op.f('ix_subscription_recipient_address'), 'subscription', ['recipient_address'], unique=False)
    op.create_index(op.f('ix_subscription_status'), 'subscription', ['status'], unique=False)
    op.create_index(op.f('ix_subscription_subscriber_user_id'), 'subscription', ['subscriber_user_id'], unique=False)
    op.create_table('suspicious_activity',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('detection_reason', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('FLAGGED', 'RESOLVED', 'CONFIRMED_FRAUD', 'FALSE_POSITIVE', name='suspiciousactivitystatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.String(length=255), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_suspicious_activity_status'), 'suspicious_activity', ['status'], unique=False)
    op.create_index(op.f('ix_suspicious_activity_user_id'), 'suspicious_activity', ['user_id'], unique=False)
    op.create_table('user_security',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('totp_enabled', sa.Boolean(), nullable=True),
    sa.Column('totp_secret', sa.String(length=1024), nullable=True),
    sa.Column('hashed_backup_codes', sa.String(length=2048), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'id')
    )
    op.create_table('vip_tier',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='viptierlevel'), nullable=False),
    sa.Column('monthly_transaction_volume', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('current_staking_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('volume_reset_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'id'),
    sa.UniqueConstraint('user_id', name='uq_vip_tier_user_id')
    )
    op.create_index(op.f('ix_vip_tier_tier'), 'vip_tier', ['tier'], unique=False)
    op.create_table('compliance_report',
    sa.Column('report_type', sa.Enum('SAR', 'CTR', 'TRAVEL_RULE', name='reporttype'), nullable=False),
    sa.Column('report_data_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'SUBMITTED', 'ACCEPTED', 'REJECTED', name='reportstatus'), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('activity_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['suspicious_activity.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_compliance_report_activity_id'), 'compliance_report', ['activity_id'], unique=False)
    op.create_index(op.f('ix_compliance_report_report_type'), 'compliance_report', ['report_type'], unique=False)
    op.create_index(op.f('ix_compliance_report_status'), 'compliance_report', ['status'], unique=False)
    op.create_index(op.f('ix_compliance_report_user_id'), 'compliance_report', ['user_id'], unique=False)
    op.create_table('deposit_transaction',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('token_address', sa.String(length=255), nullable=True),
    sa.Column('confirmations', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='depositstatus'), nullable=False),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('credited_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('internal_ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_ledger_entry_id'], ['internal_ledger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_deposit_transaction_from_address'), 'deposit_transaction', ['from_address'], unique=False)
    op.create_index(op.f('ix_deposit_transaction_status'), 'deposit_transaction', ['status'], unique=False)
    op.create_index(op.f('ix_deposit_transaction_to_address'), 'deposit_transaction', ['to_address'], unique=False)
    op.create_index(op.f('ix_deposit_transaction_tx_hash'), 'deposit_transaction', ['tx_hash'], unique=True)
    op.create_index(op.f('ix_deposit_transaction_user_id'), 'deposit_transaction', ['user_id'], unique=False)
    op.create_table('interest_accrual',
    sa.Column('staking_position_id', sa.UUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('apy_at_accrual', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('accrual_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['staking_position_id'], ['staking_position.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_interest_accrual_staking_position_id'), 'interest_accrual', ['staking_position_id'], unique=False)
    op.create_table('merchant_employee',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MANAGER', 'CASHIER', name='merchantemployeerole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_employee_email'), 'merchant_employee', ['email'], unique=True)
    op.create_index(op.f('ix_merchant_employee_merchant_id'), 'merchant_employee', ['merchant_id'], unique=False)
    op.create_table('merchant_kyc',
    sa.Column('merchant_user_id', sa.UUID(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('document_s3_key', sa.String(length=1024), nullable=False),
    sa.Column('address_proof_s3_key', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('NOT_STARTED', 'PENDING', 'APPROVED_LEVEL_1', 'APPROVED_LEVEL_2', 'APPROVED_LEVEL_3', 'REJECTED', 'NOT_VERIFIED', 'SUBMITTED', name='kycstatus'), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_user_id'], ['merchant.user_id'], ),
    sa.PrimaryKeyConstraint('merchant_user_id', 'id')
    )
    op.create_index(op.f('ix_merchant_kyc_submission_status'), 'merchant_kyc', ['status'], unique=False)
    op.create_table('merchant_settlement',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_volume_fiat', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('total_fee_fiat', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('settlement_amount_fiat', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('settlement_token_symbol', sa.String(length=20), nullable=False),
    sa.Column('settlement_token_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('settlement_wallet_address', sa.String(length=255), nullable=False),
    sa.Column('settlement_chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='settlementstatus'), nullable=False),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_settlement_merchant_id'), 'merchant_settlement', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_merchant_settlement_status'), 'merchant_settlement', ['status'], unique=False)
    op.create_index(op.f('ix_merchant_settlement_tx_hash'), 'merchant_settlement', ['tx_hash'], unique=False)
    op.create_table('merchant_terminal',
    sa.Column('merchant_id', sa.UUID(), nullable=False),
    sa.Column('terminal_name', sa.String(length=100), nullable=False),
    sa.Column('hashed_api_key', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_merchant_terminal_hashed_api_key'), 'merchant_terminal', ['hashed_api_key'], unique=True)
    op.create_index(op.f('ix_merchant_terminal_merchant_id'), 'merchant_terminal', ['merchant_id'], unique=False)
    op.create_table('payment_session',
    sa.Column('creator_user_id', sa.UUID(), nullable=True),
    sa.Column('merchant_id', sa.UUID(), nullable=True),
    sa.Column('amount_fiat', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('fiat_currency', sa.String(length=10), nullable=False),
    sa.Column('amount_token', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'EXPIRED', 'FAILED', name='paymentsessionstatus'), nullable=False),
    sa.Column('qr_nfc_payload', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchant.user_id'], ),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transaction.id'], name='fk_payment_session_txn', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_session_creator_user_id'), 'payment_session', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_payment_session_merchant_id'), 'payment_session', ['merchant_id'], unique=False)
    op.create_index(op.f('ix_payment_session_status'), 'payment_session', ['status'], unique=False)
    op.create_table('payment_transaction',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('payer_user_id', sa.UUID(), nullable=True),
    sa.Column('payer_address', sa.String(length=255), nullable=False),
    sa.Column('recipient_address', sa.String(length=255), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('amount_paid', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('token_paid_symbol', sa.String(length=20), nullable=False),
    sa.Column('token_paid_address', sa.String(length=255), nullable=True),
    sa.Column('amount_received', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('token_received_symbol', sa.String(length=20), nullable=False),
    sa.Column('fee_amount_paid', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('app_fee_amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('internal_ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_ledger_entry_id'], ['internal_ledger.id'], ),
    sa.ForeignKeyConstraint(['payer_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['payment_session.id'], name='fk_payment_txn_session', use_alter=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payment_transaction_payer_address'), 'payment_transaction', ['payer_address'], unique=False)
    op.create_index(op.f('ix_payment_transaction_payer_user_id'), 'payment_transaction', ['payer_user_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_recipient_address'), 'payment_transaction', ['recipient_address'], unique=False)
    op.create_index(op.f('ix_payment_transaction_session_id'), 'payment_transaction', ['session_id'], unique=False)
    op.create_index(op.f('ix_payment_transaction_timestamp'), 'payment_transaction', ['timestamp'], unique=False)
    op.create_index(op.f('ix_payment_transaction_tx_hash'), 'payment_transaction', ['tx_hash'], unique=True)
    op.create_table('tier_history',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('old_tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='viptierlevel'), nullable=True),
    sa.Column('new_tier', sa.Enum('BRONZE', 'SILVER', 'GOLD', 'PLATINUM', name='viptierlevel'), nullable=False),
    sa.Column('reason', sa.String(length=255), nullable=True),
    sa.Column('change_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vip_tier.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tier_history_user_id'), 'tier_history', ['user_id'], unique=False)
    op.create_table('vip_benefits_log',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('benefit_used', sa.String(length=255), nullable=False),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('usage_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['vip_tier.user_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vip_benefits_log_user_id'), 'vip_benefits_log', ['user_id'], unique=False)
    op.create_table('wallet',
    sa.Column('portfolio_id', sa.UUID(), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('derivation_path', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolio.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('portfolio_id', 'chain', 'address', name='_portfolio_chain_address_uc')
    )
    op.create_index(op.f('ix_wallet_address'), 'wallet', ['address'], unique=False)
    op.create_index(op.f('ix_wallet_portfolio_id'), 'wallet', ['portfolio_id'], unique=False)
    op.create_table('withdrawal_request',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('to_address', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('token_address', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('fee_amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('status', sa.Enum('PENDING_APPROVAL', 'APPROVED', 'PROCESSING', 'COMPLETED', 'FAILED', 'REJECTED', name='withdrawalstatus'), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('compliance_check_status', sa.Enum('PENDING', 'APPROVED', 'FLAGGED', 'REJECTED', name='compliancecheckstatus'), nullable=False),
    sa.Column('compliance_notes', sa.Text(), nullable=True),
    sa.Column('requested_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tx_hash', sa.String(length=255), nullable=True),
    sa.Column('internal_ledger_entry_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_ledger_entry_id'], ['internal_ledger.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_withdrawal_request_status'), 'withdrawal_request', ['status'], unique=False)
    op.create_index(op.f('ix_withdrawal_request_to_address'), 'withdrawal_request', ['to_address'], unique=False)
    op.create_index(op.f('ix_withdrawal_request_tx_hash'), 'withdrawal_request', ['tx_hash'], unique=True)
    op.create_index(op.f('ix_withdrawal_request_user_id'), 'withdrawal_request', ['user_id'], unique=False)
    op.create_table('bitcoin_utxo',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=64), nullable=False),
    sa.Column('vout', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('amount_satoshi', sa.Numeric(precision=20, scale=0), nullable=False),
    sa.Column('script_pub_key', sa.Text(), nullable=False),
    sa.Column('is_spent', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tx_hash', 'vout', name='_tx_hash_vout_uc')
    )
    op.create_index(op.f('ix_bitcoin_utxo_address'), 'bitcoin_utxo', ['address'], unique=False)
    op.create_index(op.f('ix_bitcoin_utxo_is_spent'), 'bitcoin_utxo', ['is_spent'], unique=False)
    op.create_index(op.f('ix_bitcoin_utxo_tx_hash'), 'bitcoin_utxo', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_bitcoin_utxo_wallet_id'), 'bitcoin_utxo', ['wallet_id'], unique=False)
    op.create_table('fee_distribution',
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('app_fee_amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('app_fee_token_symbol', sa.String(length=20), nullable=False),
    sa.Column('app_fee_recipient_address', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fee_distribution_payment_transaction_id'), 'fee_distribution', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_fee_distribution_tx_hash'), 'fee_distribution', ['tx_hash'], unique=False)
    op.create_table('invoice',
    sa.Column('creator_user_id', sa.UUID(), nullable=False),
    sa.Column('payer_email', sa.String(length=255), nullable=True),
    sa.Column('amount_fiat', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('fiat_currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('due_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'SENT', 'PAID', 'OVERDUE', 'CANCELLED', 'PENDING', name='invoicestatus'), nullable=False),
    sa.Column('payment_link_id', sa.String(length=50), nullable=False),
    sa.Column('payment_contract_address', sa.String(length=255), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['creator_user_id'], ['user_account.id'], ),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invoice_creator_user_id'), 'invoice', ['creator_user_id'], unique=False)
    op.create_index(op.f('ix_invoice_payer_email'), 'invoice', ['payer_email'], unique=False)
    op.create_index(op.f('ix_invoice_payment_link_id'), 'invoice', ['payment_link_id'], unique=True)
    op.create_index(op.f('ix_invoice_payment_transaction_id'), 'invoice', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_invoice_status'), 'invoice', ['status'], unique=False)
    op.create_table('onchain_transaction',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('chain', sa.Enum('SOLANA', 'BASE', 'POLYGON', 'ETHEREUM', 'BITCOIN', name='chain'), nullable=False),
    sa.Column('transaction_type', sa.Enum('SEND', 'RECEIVE', 'SWAP', 'PAYMENT', 'STAKE', 'UNSTAKE', 'APPROVE', 'OTHER', name='transactiontype'), nullable=False),
    sa.Column('from_address', sa.String(length=255), nullable=True),
    sa.Column('to_address', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('token_address', sa.String(length=255), nullable=True),
    sa.Column('token_symbol', sa.String(length=20), nullable=True),
    sa.Column('fee_amount', sa.Numeric(precision=36, scale=18), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED', name='transactionstatus'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('block_number', sa.Integer(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'tx_hash', name='_wallet_tx_hash_uc')
    )
    op.create_index(op.f('ix_onchain_transaction_timestamp'), 'onchain_transaction', ['timestamp'], unique=False)
    op.create_index(op.f('ix_onchain_transaction_tx_hash'), 'onchain_transaction', ['tx_hash'], unique=False)
    op.create_index(op.f('ix_onchain_transaction_wallet_id'), 'onchain_transaction', ['wallet_id'], unique=False)
    op.create_table('regulatory_submission',
    sa.Column('filing_name', sa.String(length=255), nullable=False),
    sa.Column('jurisdiction', sa.String(length=10), nullable=False),
    sa.Column('compliance_report_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submission_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('response_date', sa.DateTime(timezone=True), nullable=True),
    sa.Column('confirmation_code', sa.String(length=255), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['compliance_report_id'], ['compliance_report.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_regulatory_submission_compliance_report_id'), 'regulatory_submission', ['compliance_report_id'], unique=False)
    op.create_index(op.f('ix_regulatory_submission_jurisdiction'), 'regulatory_submission', ['jurisdiction'], unique=False)
    op.create_table('settlement_detail',
    sa.Column('settlement_id', sa.UUID(), nullable=False),
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transaction.id'], ),
    sa.ForeignKeyConstraint(['settlement_id'], ['merchant_settlement.id'], ),
    sa.PrimaryKeyConstraint('settlement_id', 'payment_transaction_id', 'id'),
    sa.UniqueConstraint('payment_transaction_id')
    )
    op.create_table('swap_transaction',
    sa.Column('payment_transaction_id', sa.UUID(), nullable=False),
    sa.Column('tx_hash', sa.String(length=255), nullable=False),
    sa.Column('aggregator', sa.String(length=50), nullable=False),
    sa.Column('token_in_address', sa.String(length=255), nullable=True),
    sa.Column('token_in_symbol', sa.String(length=20), nullable=False),
    sa.Column('amount_in', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('token_out_address', sa.String(length=255), nullable=True),
    sa.Column('token_out_symbol', sa.String(length=20), nullable=False),
    sa.Column('amount_out', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_transaction_id'], ['payment_transaction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_swap_transaction_payment_transaction_id'), 'swap_transaction', ['payment_transaction_id'], unique=False)
    op.create_index(op.f('ix_swap_transaction_tx_hash'), 'swap_transaction', ['tx_hash'], unique=False)
    op.create_table('token_balance',
    sa.Column('wallet_id', sa.UUID(), nullable=False),
    sa.Column('token_coingecko_id', sa.String(length=100), nullable=True),
    sa.Column('token_address', sa.String(length=255), nullable=True),
    sa.Column('token_symbol', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.Numeric(precision=36, scale=18), nullable=False),
    sa.Column('usd_value', sa.Numeric(precision=20, scale=4), nullable=False),
    sa.Column('last_updated', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['wallet_id'], ['wallet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('wallet_id', 'token_address', name='_wallet_token_uc')
    )
    op.create_index(op.f('ix_token_balance_token_address'), 'token_balance', ['token_address'], unique=False)
    op.create_index(op.f('ix_token_balance_token_coingecko_id'), 'token_balance', ['token_coingecko_id'], unique=False)
    op.create_index(op.f('ix_token_balance_wallet_id'), 'token_balance', ['wallet_id'], unique=False)
    op.create_table('travel_rule_record',
    sa.Column('onchain_transaction_id', sa.UUID(), nullable=True),
    sa.Column('internal_ledger_id', sa.UUID(), nullable=True),
    sa.Column('sender_user_id', sa.UUID(), nullable=False),
    sa.Column('sender_pii_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('recipient_pii_encrypted', sa.String(length=2048), nullable=False),
    sa.Column('destination_vasp', sa.String(length=255), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'COMPLETED', 'FAILED', name='compliancestatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['internal_ledger_id'], ['internal_ledger.id'], ),
    sa.ForeignKeyConstraint(['onchain_transaction_id'], ['onchain_transaction.id'], ),
    sa.ForeignKeyConstraint(['sender_user_id'], ['user_account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_travel_rule_record_internal_ledger_id'), 'travel_rule_record', ['internal_ledger_id'], unique=False)
    op.create_index(op.f('ix_travel_rule_record_onchain_transaction_id'), 'travel_rule_record', ['onchain_transaction_id'], unique=False)
    op.create_index(op.f('ix_travel_rule_record_sender_user_id'), 'travel_rule_record', ['sender_user_id'], unique=False)
    op.create_index(op.f('ix_travel_rule_record_status'), 'travel_rule_record', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_travel_rule_record_status'), table_name='travel_rule_record')
    op.drop_index(op.f('ix_travel_rule_record_sender_user_id'), table_name='travel_rule_record')
    op.drop_index(op.f('ix_travel_rule_record_onchain_transaction_id'), table_name='travel_rule_record')
    op.drop_index(op.f('ix_travel_rule_record_internal_ledger_id'), table_name='travel_rule_record')
    op.drop_table('travel_rule_record')
    op.drop_index(op.f('ix_token_balance_wallet_id'), table_name='token_balance')
    op.drop_index(op.f('ix_token_balance_token_coingecko_id'), table_name='token_balance')
    op.drop_index(op.f('ix_token_balance_token_address'), table_name='token_balance')
    op.drop_table('token_balance')
    op.drop_index(op.f('ix_swap_transaction_tx_hash'), table_name='swap_transaction')
    op.drop_index(op.f('ix_swap_transaction_payment_transaction_id'), table_name='swap_transaction')
    op.drop_table('swap_transaction')
    op.drop_table('settlement_detail')
    op.drop_index(op.f('ix_regulatory_submission_jurisdiction'), table_name='regulatory_submission')
    op.drop_index(op.f('ix_regulatory_submission_compliance_report_id'), table_name='regulatory_submission')
    op.drop_table('regulatory_submission')
    op.drop_index(op.f('ix_onchain_transaction_wallet_id'), table_name='onchain_transaction')
    op.drop_index(op.f('ix_onchain_transaction_tx_hash'), table_name='onchain_transaction')
    op.drop_index(op.f('ix_onchain_transaction_timestamp'), table_name='onchain_transaction')
    op.drop_table('onchain_transaction')
    op.drop_index(op.f('ix_invoice_status'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_payment_transaction_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_payment_link_id'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_payer_email'), table_name='invoice')
    op.drop_index(op.f('ix_invoice_creator_user_id'), table_name='invoice')
    op.drop_table('invoice')
    op.drop_index(op.f('ix_fee_distribution_tx_hash'), table_name='fee_distribution')
    op.drop_index(op.f('ix_fee_distribution_payment_transaction_id'), table_name='fee_distribution')
    op.drop_table('fee_distribution')
    op.drop_index(op.f('ix_bitcoin_utxo_wallet_id'), table_name='bitcoin_utxo')
    op.drop_index(op.f('ix_bitcoin_utxo_tx_hash'), table_name='bitcoin_utxo')
    op.drop_index(op.f('ix_bitcoin_utxo_is_spent'), table_name='bitcoin_utxo')
    op.drop_index(op.f('ix_bitcoin_utxo_address'), table_name='bitcoin_utxo')
    op.drop_table('bitcoin_utxo')
    op.drop_index(op.f('ix_withdrawal_request_user_id'), table_name='withdrawal_request')
    op.drop_index(op.f('ix_withdrawal_request_tx_hash'), table_name='withdrawal_request')
    op.drop_index(op.f('ix_withdrawal_request_to_address'), table_name='withdrawal_request')
    op.drop_index(op.f('ix_withdrawal_request_status'), table_name='withdrawal_request')
    op.drop_table('withdrawal_request')
    op.drop_index(op.f('ix_wallet_portfolio_id'), table_name='wallet')
    op.drop_index(op.f('ix_wallet_address'), table_name='wallet')
    op.drop_table('wallet')
    op.drop_index(op.f('ix_vip_benefits_log_user_id'), table_name='vip_benefits_log')
    op.drop_table('vip_benefits_log')
    op.drop_index(op.f('ix_tier_history_user_id'), table_name='tier_history')
    op.drop_table('tier_history')
    op.drop_index(op.f('ix_payment_transaction_tx_hash'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_timestamp'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_session_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_recipient_address'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_payer_user_id'), table_name='payment_transaction')
    op.drop_index(op.f('ix_payment_transaction_payer_address'), table_name='payment_transaction')
    op.drop_table('payment_transaction')
    op.drop_index(op.f('ix_payment_session_status'), table_name='payment_session')
    op.drop_index(op.f('ix_payment_session_merchant_id'), table_name='payment_session')
    op.drop_index(op.f('ix_payment_session_creator_user_id'), table_name='payment_session')
    op.drop_table('payment_session')
    op.drop_index(op.f('ix_merchant_terminal_merchant_id'), table_name='merchant_terminal')
    op.drop_index(op.f('ix_merchant_terminal_hashed_api_key'), table_name='merchant_terminal')
    op.drop_table('merchant_terminal')
    op.drop_index(op.f('ix_merchant_settlement_tx_hash'), table_name='merchant_settlement')
    op.drop_index(op.f('ix_merchant_settlement_status'), table_name='merchant_settlement')
    op.drop_index(op.f('ix_merchant_settlement_merchant_id'), table_name='merchant_settlement')
    op.drop_table('merchant_settlement')
    op.drop_index(op.f('ix_merchant_kyc_status'), table_name='merchant_kyc')
    op.drop_table('merchant_kyc')
    op.drop_index(op.f('ix_merchant_employee_merchant_id'), table_name='merchant_employee')
    op.drop_index(op.f('ix_merchant_employee_email'), table_name='merchant_employee')
    op.drop_table('merchant_employee')
    op.drop_index(op.f('ix_interest_accrual_staking_position_id'), table_name='interest_accrual')
    op.drop_table('interest_accrual')
    op.drop_index(op.f('ix_deposit_transaction_user_id'), table_name='deposit_transaction')
    op.drop_index(op.f('ix_deposit_transaction_tx_hash'), table_name='deposit_transaction')
    op.drop_index(op.f('ix_deposit_transaction_to_address'), table_name='deposit_transaction')
    op.drop_index(op.f('ix_deposit_transaction_status'), table_name='deposit_transaction')
    op.drop_index(op.f('ix_deposit_transaction_from_address'), table_name='deposit_transaction')
    op.drop_table('deposit_transaction')
    op.drop_index(op.f('ix_compliance_report_user_id'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_status'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_report_type'), table_name='compliance_report')
    op.drop_index(op.f('ix_compliance_report_activity_id'), table_name='compliance_report')
    op.drop_table('compliance_report')
    op.drop_index(op.f('ix_vip_tier_tier'), table_name='vip_tier')
    op.drop_table('vip_tier')
    op.drop_table('user_security')
    op.drop_index(op.f('ix_suspicious_activity_user_id'), table_name='suspicious_activity')
    op.drop_index(op.f('ix_suspicious_activity_status'), table_name='suspicious_activity')
    op.drop_table('suspicious_activity')
    op.drop_index(op.f('ix_subscription_subscriber_user_id'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_status'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_recipient_address'), table_name='subscription')
    op.drop_index(op.f('ix_subscription_next_execution_date'), table_name='subscription')
    op.drop_table('subscription')
    op.drop_index(op.f('ix_staking_position_user_id'), table_name='staking_position')
    op.drop_index(op.f('ix_staking_position_token_symbol'), table_name='staking_position')
    op.drop_table('staking_position')
    op.drop_index(op.f('ix_pull_payment_approval_status'), table_name='pull_payment_approval')
    op.drop_index(op.f('ix_pull_payment_approval_recipient_address'), table_name='pull_payment_approval')
    op.drop_index(op.f('ix_pull_payment_approval_period_end_date'), table_name='pull_payment_approval')
    op.drop_index(op.f('ix_pull_payment_approval_approver_user_id'), table_name='pull_payment_approval')
    op.drop_table('pull_payment_approval')
    op.drop_index(op.f('ix_price_alert_user_id'), table_name='price_alert')
    op.drop_index(op.f('ix_price_alert_status'), table_name='price_alert')
    op.drop_index(op.f('ix_price_alert_coin_id'), table_name='price_alert')
    op.drop_table('price_alert')
    op.drop_index(op.f('ix_portfolio_user_id'), table_name='portfolio')
    op.drop_table('portfolio')
    op.drop_index(op.f('ix_merchant_registration_number'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_kyc_status'), table_name='merchant')
    op.drop_index(op.f('ix_merchant_business_name'), table_name='merchant')
    op.drop_table('merchant')
    op.drop_index(op.f('ix_kyc_submission_user_id'), table_name='kyc_submission')
    op.drop_index(op.f('ix_kyc_submission_external_submission_id'), table_name='kyc_submission')
    op.drop_table('kyc_submission')
    op.drop_index(op.f('ix_internal_ledger_user_id'), table_name='internal_ledger')
    op.drop_index(op.f('ix_internal_ledger_transaction_id'), table_name='internal_ledger')
    op.drop_index(op.f('ix_internal_ledger_token_symbol'), table_name='internal_ledger')
    op.drop_index(op.f('ix_internal_ledger_related_user_id'), table_name='internal_ledger')
    op.drop_index(op.f('ix_internal_ledger_related_tx_hash'), table_name='internal_ledger')
    op.drop_index(op.f('ix_internal_ledger_entry_type'), table_name='internal_ledger')
    op.drop_table('internal_ledger')
    op.drop_index(op.f('ix_blockchain_screening_user_id'), table_name='blockchain_screening')
    op.drop_index(op.f('ix_blockchain_screening_risk_rating'), table_name='blockchain_screening')
    op.drop_index(op.f('ix_blockchain_screening_chain'), table_name='blockchain_screening')
    op.drop_index(op.f('ix_blockchain_screening_address'), table_name='blockchain_screening')
    op.drop_index(op.f('ix_blockchain_screening_action_taken'), table_name='blockchain_screening')
    op.drop_table('blockchain_screening')
    op.drop_index(op.f('ix_address_whitelist_user_id'), table_name='address_whitelist')
    op.drop_index(op.f('ix_address_whitelist_address'), table_name='address_whitelist')
    op.drop_table('address_whitelist')
    op.drop_index('ix_user_username_active', table_name='user_account', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index('ix_user_email_active', table_name='user_account', postgresql_where=sa.text('is_deleted = false'))
    op.drop_index(op.f('ix_user_account_username'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_is_deleted'), table_name='user_account')
    op.drop_index(op.f('ix_user_account_email'), table_name='user_account')
    op.drop_table('user_account')
    op.drop_index(op.f('ix_smart_contract_is_active'), table_name='smart_contract')
    op.drop_index(op.f('ix_smart_contract_contract_type'), table_name='smart_contract')
    op.drop_index(op.f('ix_smart_contract_chain'), table_name='smart_contract')
    op.drop_index(op.f('ix_smart_contract_address'), table_name='smart_contract')
    op.drop_table('smart_contract')
    op.drop_index(op.f('ix_price_snapshot_coin_id'), table_name='price_snapshot')
    op.drop_table('price_snapshot')
    op.drop_index(op.f('ix_msb_license_jurisdiction'), table_name='msb_license')
    op.drop_table('msb_license')
    # ### end Alembic commands ###