import uuid
from decimal import Decimal
from typing import List, Optional, Any, Dict

from pydantic import BaseModel, Field, AnyHttpUrl

from app.utils.enums import Chain
from app.schemas.transaction import FeeEstimate # Re-use FeeEstimate

# --- Schemas for Swap Quotes ---

class SwapQuoteRequest(BaseModel):
    """
    Schema for requesting a swap quote from a DEX aggregator.
    """
    from_chain: Chain
    from_token_address: Optional[str] = Field(None, description="Address of the token to sell (null for native)")
    from_token_symbol: str # Symbol is helpful for display/lookup
    
    to_chain: Chain # For cross-chain swaps, otherwise same as from_chain
    to_token_address: Optional[str] = Field(None, description="Address of the token to buy (null for native)")
    to_token_symbol: str
    
    amount: Decimal = Field(..., gt=0, description="Amount of 'from_token' to sell (in standard units)")
    
    # User's wallet address for context (e.g., checking allowances, balances)
    user_address: str
    
    # Optional: Slippage tolerance percentage (e.g., 0.5 for 0.5%)
    slippage_percentage: Decimal = Field(0.5, ge=0, le=5) # Default 0.5%, max 5%

class SwapRouteStep(BaseModel):
    """ Represents a single step within a swap route. """
    dex: str = Field(..., description="Name of the DEX used for this step")
    from_token_symbol: str
    to_token_symbol: str
    # Add more details if provided by the aggregator (e.g., pool address)

class SwapQuoteResponse(BaseModel):
    """
    Schema for the response containing a swap quote from the aggregator.
    """
    from_chain: Chain
    from_token_symbol: str
    from_token_address: Optional[str]
    from_amount: Decimal
    
    to_chain: Chain
    to_token_symbol: str
    to_token_address: Optional[str]
    estimated_to_amount: Decimal = Field(..., description="Estimated amount of 'to_token' received")
    minimum_to_amount: Optional[Decimal] = Field(None, description="Minimum amount guaranteed after slippage")
    
    price_impact_percentage: Optional[Decimal] = Field(None, description="Estimated price impact of the swap")
    
    # Estimated gas/network fees
    fee_estimate: FeeEstimate
    
    # Details of the swap route (if provided by aggregator)
    route: Optional[List[SwapRouteStep]] = None
    
    # Aggregator-specific data needed for executing the swap
    aggregator_data: Optional[Dict[str, Any]] = Field(None, description="Data needed by aggregator for swap execution")
    
    # Unique identifier for the quote, might be needed for execution
    quote_id: Optional[str] = None


# --- Schemas for Preparing Swap Transactions ---

class SwapPrepareRequest(BaseModel):
    """
    Schema for requesting the backend to prepare the actual swap transaction
    based on a selected quote.
    """
    portfolio_id: uuid.UUID
    wallet_id: uuid.UUID # Wallet performing the swap
    
    # Information from the chosen SwapQuoteResponse
    from_chain: Chain
    from_token_address: Optional[str]
    from_token_symbol: str
    from_amount: Decimal
    
    to_chain: Chain
    to_token_address: Optional[str]
    to_token_symbol: str
    
    user_address: str # The specific address from the wallet_id
    
    # Include quote_id or aggregator_data if required by the aggregator API
    quote_id: Optional[str] = None
    aggregator_data: Optional[Dict[str, Any]] = None
    
    # Allow overriding slippage if needed, otherwise use quote's context
    slippage_percentage: Optional[Decimal] = Field(None, ge=0, le=5)

# SwapPrepareResponse would be similar to TransactionPrepareResponse,
# containing the unsigned swap transaction data generated by the aggregator/backend.
# from app.schemas.transaction import TransactionPrepareResponse as SwapPrepareResponse

# SwapBroadcastRequest would be similar to TransactionBroadcastRequest,
# submitting the signed swap transaction.
# from app.schemas.transaction import TransactionBroadcastRequest as SwapBroadcastRequest

# SwapBroadcastResponse would be similar to TransactionBroadcastResponse,
# providing the tx_hash of the swap.
# from app.schemas.transaction import TransactionBroadcastResponse as SwapBroadcastResponse
