import uuid
from decimal import Decimal
from typing import List, Optional, Any, Dict

from pydantic import BaseModel, Field, field_validator

from app.utils.enums import Chain
from app.schemas.transaction import FeeEstimate

class SwapQuoteRequest(BaseModel):
    """
    Schema for requesting a swap quote.
    """
    from_chain: Chain
    from_token_address: Optional[str] = None
    from_token_symbol: str
    
    to_chain: Chain
    to_token_address: Optional[str] = None
    to_token_symbol: str
    
    amount: Decimal = Field(..., gt=0)
    user_address: str
    
    # SAFETY FIX: Max slippage capped at 50% (user error protection), default 0.5%
    slippage_percentage: Decimal = Field(0.5, ge=0, le=50) 

    @field_validator("user_address")
    @classmethod
    def validate_user_address(cls, v: str) -> str:
        if len(v) < 20: # Basic length check
            raise ValueError("Invalid wallet address length.")
        return v

class SwapQuoteResponse(BaseModel):
    from_chain: Chain
    from_token_symbol: str
    from_token_address: Optional[str]
    from_amount: Decimal
    
    to_chain: Chain
    to_token_symbol: str
    to_token_address: Optional[str]
    estimated_to_amount: Decimal
    minimum_to_amount: Optional[Decimal]
    
    price_impact_percentage: Optional[Decimal]
    fee_estimate: FeeEstimate
    
    aggregator_data: Optional[Dict[str, Any]] = None
    quote_id: Optional[str] = None


class SwapRouteStep(BaseModel):
    """ Represents a single step within a swap route. """
    dex: str = Field(..., description="Name of the DEX used for this step")
    from_token_symbol: str
    to_token_symbol: str
    # Add more details if provided by the aggregator (e.g., pool address)



# --- Schemas for Preparing Swap Transactions ---

class SwapPrepareRequest(BaseModel):
    """
    Schema for requesting the backend to prepare the actual swap transaction
    based on a selected quote.
    """
    portfolio_id: uuid.UUID
    wallet_id: uuid.UUID # Wallet performing the swap
    
    # Information from the chosen SwapQuoteResponse
    from_chain: Chain
    from_token_address: Optional[str]
    from_token_symbol: str
    from_amount: Decimal
    
    to_chain: Chain
    to_token_address: Optional[str]
    to_token_symbol: str
    
    user_address: str # The specific address from the wallet_id
    
    # Include quote_id or aggregator_data if required by the aggregator API
    quote_id: Optional[str] = None
    aggregator_data: Optional[Dict[str, Any]] = None
    
    # Allow overriding slippage if needed, otherwise use quote's context
    slippage_percentage: Optional[Decimal] = Field(None, ge=0, le=5)

# SwapPrepareResponse would be similar to TransactionPrepareResponse,
# containing the unsigned swap transaction data generated by the aggregator/backend.
# from app.schemas.transaction import TransactionPrepareResponse as SwapPrepareResponse

# SwapBroadcastRequest would be similar to TransactionBroadcastRequest,
# submitting the signed swap transaction.
# from app.schemas.transaction import TransactionBroadcastRequest as SwapBroadcastRequest

# SwapBroadcastResponse would be similar to TransactionBroadcastResponse,
# providing the tx_hash of the swap.
# from app.schemas.transaction import TransactionBroadcastResponse as SwapBroadcastResponse
