from typing import Any
import uuid

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.api.v1.deps import get_db, get_current_active_user
from app.models.user import User
from app.schemas.transaction import (
    TransactionPrepareRequest,
    TransactionPrepareResponse,
    TransactionBroadcastRequest,
    TransactionBroadcastResponse
)
from app.services.transaction_service import TransactionService
from app.utils.exceptions import (
    BadRequestException,
    InsufficientBalanceException,
    NotFoundException,
    TransactionFailedException
)

router = APIRouter()

@router.post("/prepare", response_model=TransactionPrepareResponse)
async def prepare_transaction(
    tx_request: TransactionPrepareRequest,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    """
    Prepare an on-chain transaction.
    
    Returns an **unsigned** transaction object (format depends on chain) and a fee estimate.
    The mobile app should use this data to sign the transaction locally using the private key.
    """
    transaction_service = TransactionService(db)
    
    try:
        response = await transaction_service.prepare_transaction(
            user_id=current_user.id,
            request=tx_request
        )
        return response
        
    except (InsufficientBalanceException, NotFoundException) as e:
        # These are expected errors (400/404)
        raise e
    except Exception as e:
        # Unexpected errors during prep (e.g., RPC down)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to prepare transaction: {str(e)}"
        )


@router.post("/broadcast", response_model=TransactionBroadcastResponse)
async def broadcast_transaction(
    tx_broadcast: TransactionBroadcastRequest,
    current_user: User = Depends(get_current_active_user),
    db: AsyncSession = Depends(get_db),
) -> Any:
    """
    Broadcast a **signed** transaction to the blockchain network.
    
    The 'signed_tx' field should contain the hex (EVM/BTC) or base64 (Solana) string
    generated by the mobile app after signing the prepared payload.
    """
    transaction_service = TransactionService(db)
    
    try:
        response = await transaction_service.broadcast_transaction(
            user_id=current_user.id,
            request=tx_broadcast
        )
        return response
        
    except TransactionFailedException as e:
        # The node rejected the transaction (e.g., nonce too low, signature invalid)
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail=e.detail
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Broadcast failed: {str(e)}"
        )
        

# Note: Transaction History endpoint (GET /) would typically go here.
# It would query the 'onchain_transaction' table via a TransactionService.get_history() method.
# Skipped for now as focus is on the send flow (Section D).